I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cable.rpy", line 17, in script
    g " eh vous deux comment vous êtes arriver là ?!!"
Exception: Sayer 'g' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cable.rpy", line 17, in script
    g " eh vous deux comment vous êtes arriver là ?!!"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'g' is not defined.

Windows-10-10.0.18362
Ren'Py 7.4.2.1292
Robot et humain 1.0
Wed Feb 17 17:05:34 2021
